### ISSUE TITLE
SoundCloud support

### ISSUE THREAD

**Issue by Glavin001** [tastejs/TasteMusic#5]
### SoundCloud
- [x] We will need to [obtain a client id](http://soundcloud.com/you/apps).
- [x] To lookup the track with the posted URLs, use the [/resolve](http://developers.soundcloud.com/docs/api/reference#apps) API request.
- [ ] There's a [Widget for embedding and playing tracks](http://developers.soundcloud.com/docs/api/guide#playing)

**Comment by sindresorhus** [comment]
:+1:

**Comment by passy** [comment]
SoundCloud's API is fantastic. :)

**Comment by Glavin001** [comment]
### SoundCloud App info:

Title: TasteMusic
Website: https://github.com/tastejs/TasteMusic
Client ID: 6aeb01b043ebc13df5e211ab3187464f
Client Secret: 2cadf9151daca8bd94c9ba93b6b2bf66
Redirection URI: (empty)
End User Authorization: https://soundcloud.com/connect
Token: https://api.soundcloud.com/oauth2/token
